// Image segmentation with a pretrained U-Net (qubvel-hf/unet-with-metadata,
// segmentation_models_pytorch.Unet with ResNet34 encoder, trained on PASCAL VOC
// binary foreground masks).
//
// One Metal pass: stem -> ResNet34 encoder -> decoder w/ skips -> 1x1 head ->
// sigmoid. Output is a per-pixel foreground probability; we threshold at 0.5.
//
// Usage:
//   ./segmentation [input.jpg]  (default: build/example/segmentation/data/input.jpg)
// Outputs:
//   build/example/segmentation/out/{input.png,mask.png,overlay.png}

#define STB_IMAGE_IMPLEMENTATION
#define STB_IMAGE_WRITE_IMPLEMENTATION
#include "stb_image.h"
#include "stb_image_write.h"

#include "cg.h"
#include "metal_executor.h"
#include "safetensors.h"
#include "unet.h"
#include "seg_paths.h"     // generated by CMake: SEG_WEIGHTS_PATH, SEG_INPUT_PATH, SEG_OUT_DIR

#include <algorithm>
#include <chrono>
#include <cmath>
#include <cstdint>
#include <cstring>
#include <filesystem>
#include <iostream>
#include <stdexcept>
#include <string>
#include <vector>

namespace fs = std::filesystem;

constexpr int IMG_DIM = 256;        // must be a multiple of 32. Model was trained at 256.
// ImageNet normalization — the ResNet34 encoder was ImageNet-pretrained,
// so input is normalized with the standard ImageNet stats.
static const float MEAN[3] = {0.485f, 0.456f, 0.406f};
static const float STD [3] = {0.229f, 0.224f, 0.225f};

// ---- Image I/O -------------------------------------------------------------

struct Rgb8 { std::vector<uint8_t> px; int w, h; };

static Rgb8 load_rgb(const std::string& path) {
    int w, h, ch;
    uint8_t* raw = stbi_load(path.c_str(), &w, &h, &ch, 3);    // force 3 channels
    if (!raw) throw std::runtime_error("cannot load image: " + path
                                       + " (stbi: " + stbi_failure_reason() + ")");
    Rgb8 out;
    out.w = w; out.h = h;
    out.px.assign(raw, raw + w * h * 3);
    stbi_image_free(raw);
    return out;
}

static void save_rgb(const std::string& path, const Rgb8& img) {
    if (!stbi_write_png(path.c_str(), img.w, img.h, 3, img.px.data(), img.w * 3))
        throw std::runtime_error("stbi_write_png failed: " + path);
}
static void save_gray(const std::string& path, const std::vector<uint8_t>& g, int w, int h) {
    if (!stbi_write_png(path.c_str(), w, h, 1, g.data(), w))
        throw std::runtime_error("stbi_write_png failed: " + path);
}

// Center-crop to square, then bilinear resize to dim x dim.
static Rgb8 center_crop_resize(const Rgb8& src, int dim) {
    int side = std::min(src.w, src.h);
    int x0 = (src.w - side) / 2;
    int y0 = (src.h - side) / 2;

    Rgb8 out;
    out.w = dim; out.h = dim;
    out.px.assign(dim * dim * 3, 0);

    auto sample = [&](float fx, float fy, int c) -> float {
        int x = (int)std::floor(fx);
        int y = (int)std::floor(fy);
        float dx = fx - x;
        float dy = fy - y;
        int x1 = std::min(x + 1, side - 1);
        int y1 = std::min(y + 1, side - 1);
        x = std::max(0, std::min(x, side - 1));
        y = std::max(0, std::min(y, side - 1));
        auto get = [&](int xi, int yi) {
            int sx = x0 + xi, sy = y0 + yi;
            return (float)src.px[(sy * src.w + sx) * 3 + c];
        };
        float v00 = get(x,  y ), v10 = get(x1, y );
        float v01 = get(x,  y1), v11 = get(x1, y1);
        return (1 - dx) * (1 - dy) * v00 + dx * (1 - dy) * v10
             + (1 - dx) *  dy      * v01 + dx *  dy      * v11;
    };

    float scale = (float)side / (float)dim;
    for (int j = 0; j < dim; ++j)
        for (int i = 0; i < dim; ++i)
            for (int c = 0; c < 3; ++c) {
                float v = sample((i + 0.5f) * scale - 0.5f,
                                 (j + 0.5f) * scale - 0.5f, c);
                out.px[(j * dim + i) * 3 + c] = (uint8_t)std::clamp((int)std::round(v), 0, 255);
            }
    return out;
}

// ---- Tensor packing --------------------------------------------------------

// [H, W, 3] uint8 -> [1, 3, H, W] float, ImageNet-normalized.
static cg::Tensor to_nchw_normalized(const Rgb8& img) {
    int H = img.h, W = img.w;
    cg::Tensor t({1, 3, H, W});
    for (int c = 0; c < 3; ++c)
        for (int y = 0; y < H; ++y)
            for (int x = 0; x < W; ++x) {
                float v = img.px[(y * W + x) * 3 + c] / 255.0f;
                t[((0 * 3 + c) * H + y) * W + x] = (v - MEAN[c]) / STD[c];
            }
    return t;
}

// ---- Mask -> visualization -------------------------------------------------

// Tint pixels red where mask == 1.
static Rgb8 make_overlay(const Rgb8& img, const std::vector<uint8_t>& mask) {
    Rgb8 out = img;
    int N = img.w * img.h;
    for (int i = 0; i < N; ++i) {
        if (mask[i]) {
            uint8_t r = out.px[i * 3 + 0], g = out.px[i * 3 + 1], b = out.px[i * 3 + 2];
            out.px[i * 3 + 0] = (uint8_t)((r + 255) / 2);
            out.px[i * 3 + 1] = (uint8_t)(g / 2);
            out.px[i * 3 + 2] = (uint8_t)(b / 2);
        }
    }
    return out;
}

// ---- Main ------------------------------------------------------------------

int main(int argc, char** argv) {
    // usage: segmentation [--bench N] [input.jpg [output_dir]]
    //   --bench N : run inference N+1 times (1 warmup + N timed) and print stats;
    //               skip image preprocessing time, exclude device->host result fetch.
    int bench_iters = 0;
    int argi = 1;
    if (argc > 1 && std::string(argv[1]) == "--bench") {
        if (argc < 3) { std::cerr << "--bench needs N\n"; return 2; }
        bench_iters = std::atoi(argv[2]);
        argi = 3;
    }
    std::string in_path  = (argc > argi)     ? argv[argi]     : SEG_INPUT_PATH;
    std::string out_dir  = (argc > argi + 1) ? argv[argi + 1] : SEG_OUT_DIR;
    std::string weights  = SEG_WEIGHTS_PATH;

    fs::create_directories(out_dir);

    Rgb8       raw   = load_rgb(in_path);
    Rgb8       sized = center_crop_resize(raw, IMG_DIM);
    auto       sf    = safetensors::load(weights);
    seg::UNet  model;
    model.load_safetensors(sf);
    save_rgb(out_dir + "/input.png", sized);

    cg::Tensor X = to_nchw_normalized(sized);
    cg::ComputeGraph g(cg::Precision::F16);
    auto x_t = cg::nn::input(g, "X", X);
    auto y_t = model.forward(x_t);
    auto* y  = y_t.node();

    cg::metal::Executor exec(cg::metal::Executor::MatMul::MPP);

    if (bench_iters > 0) {
        // Warmup, then N timed iters. exec.reset() flushes the previous run's
        // host cache but keeps device buffers alive for reuse.
        exec.reset();
        g.accept(exec, y);
        (void)exec.result(y);

        std::vector<double> ms(bench_iters);
        for (int i = 0; i < bench_iters; ++i) {
            exec.reset();
            auto t0 = std::chrono::high_resolution_clock::now();
            g.accept(exec, y);
            (void)exec.result(y);
            auto t1 = std::chrono::high_resolution_clock::now();
            ms[i] = std::chrono::duration<double, std::milli>(t1 - t0).count();
        }
        double sum = 0.0, mn = ms[0], mx = ms[0];
        for (double v : ms) { sum += v; if (v < mn) mn = v; if (v > mx) mx = v; }
        double mean = sum / bench_iters;
        double var = 0.0;
        for (double v : ms) var += (v - mean) * (v - mean);
        std::cout << bench_iters << " iters @ " << IMG_DIM << "x" << IMG_DIM
                  << "  mean " << mean
                  << "  min " << mn << "  max " << mx
                  << "  std " << std::sqrt(var / bench_iters) << " ms\n";
        return 0;
    }

    g.accept(exec, y);
    const cg::Tensor& out = exec.result(y);
    if (out.shape() != std::vector<int>({1, 1, IMG_DIM, IMG_DIM}))
        throw std::runtime_error("unexpected output shape");

    int N_px = IMG_DIM * IMG_DIM;
    std::vector<uint8_t> mask(N_px), mask_gray(N_px);
    for (int i = 0; i < N_px; ++i) {
        float p = 1.0f / (1.0f + std::exp(-out[i]));
        mask[i]      = p > 0.5f;
        mask_gray[i] = mask[i] ? 255 : 0;
    }
    save_gray(out_dir + "/mask.png",    mask_gray, IMG_DIM, IMG_DIM);
    save_rgb (out_dir + "/overlay.png", make_overlay(sized, mask));
    return 0;
}
